spring.profiles.active: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver

# Swagger configuration
springdoc:
  packages-to-scan: com.geniushyeon.architecture