spring.profiles.active: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
  data:
    redis:
      port: 6379
      host: localhost

# Swagger configuration
springdoc:
  packages-to-scan: com.geniushyeon.architecture

# JWT
jwt:
  access-token:
    secret: RSofQYXuYnt2ik0CD0kMj5C6gJK45QRSofQYXuYnt2ik0CD0kMj5C6gJK45Q
  refresh-token:
    secret: vZVNPaPB6giQ9c11vTD8Fi1v2Sk7bMvZVNPaPB6giQ9c11vTD8Fi1v2Sk7bM